export const seeds = [
  {
    id: '1',
    name: 'Apple',
    type: 'Fruit',
    quantity: 100,
    minGrowthTime: '60 days',
    maxGrowthTime: '90 days',
    preferredWeather: 'Temperate',
    info: 'A sweet fruit that grows on trees.',
  },
  {
    id: '2',
    name: 'Tomato',
    type: 'Vegetable',
    quantity: 50,
    minGrowthTime: '60 days',
    maxGrowthTime: '80 days',
    preferredWeather: 'Warm',
    info: 'A juicy vegetable often used in salads.',
  },
  {
    id: '3',
    name: 'Carrot',
    type: 'Vegetable',
    quantity: 75,
    minGrowthTime: '70 days',
    maxGrowthTime: '80 days',
    preferredWeather: 'Cool',
    info: 'A root vegetable that grows best in cool climates.',
  },
];