import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    resizeMode: 'cover',
    paddingHorizontal: 15,
    paddingTop: 40,
    backgroundColor: '#f0f8ff',
  },
  header: {
    marginBottom: 15,
    alignItems: 'center',
  },
  headerText: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#2e8b57',
    textShadowColor: '#aaa',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  searchBar: {
    height: 40,
    backgroundColor: 'rgba(255,255,255,0.85)',
    borderRadius: 8,
    paddingHorizontal: 12,
    fontSize: 16,
    color: '#333',
    marginBottom: 10,
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  sortButton: {
    flex: 1,
    backgroundColor: '#2e8b57',
    paddingVertical: 10,
    marginHorizontal: 5,
    borderRadius: 8,
    alignItems: 'center',
  },
  buttonText: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 14,
  },
  noSeedsText: {
    marginTop: 50,
    textAlign: 'center',
    fontSize: 18,
    color: '#555',
  },
  seedItem: {
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    paddingVertical: 14,
    paddingHorizontal: 20,
    marginBottom: 10,
    borderRadius: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    elevation: 2,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 5,
  },
  seedName: {
    fontSize: 16,
    fontWeight: '700',
    color: '#2e8b57',
  },
  seedQuantity: {
    fontSize: 14,
    color: '#555',
  },
  addButton: {
    position: 'absolute',
    bottom: 30,
    right: 20,
    backgroundColor: '#2e8b57',
    paddingVertical: 14,
    paddingHorizontal: 25,
    borderRadius: 30,
    elevation: 5,
    shadowColor: '#000',
    shadowOpacity: 0.3,
    shadowOffset: { width: 0, height: 3 },
    shadowRadius: 5,
  },
  addButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 0,
  },
  addSeedModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    top: 40,
    height: height - 40,
  },
  modalContainer: {
    width: '90%',
    backgroundColor: '#fff',
    borderRadius: 15,
    paddingVertical: 20,
    paddingHorizontal: 25,
    maxHeight: height * 0.6,
    elevation: 5,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 8,
  },
  addSeedModalContainer: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    borderWidth: 1,
    borderColor: '#ccc',
    width: '100%',
    minHeight: 560, // Adjusted for larger buttons
    maxHeight: height - 40,
    elevation: 10,
    shadowColor: '#000',
    shadowOpacity: 0.4,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 12,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 10,
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: '900',
    color: '#2e8b57',
    textAlign: 'center',
    marginBottom: 8,
  },
  closeButton: {
    padding: 8,
  },
  closeButtonText: {
    fontSize: 20,
    color: '#2e8b57',
    fontWeight: 'bold',
  },
  modalContent: {
    paddingHorizontal: 20,
    paddingVertical: 15,
    paddingBottom: 15,
  },
  modalDivider: {
    height: 1,
    backgroundColor: '#ddd',
    marginBottom: 8,
  },
  modalFooter: {
    padding: 20,
    height: 70, // Increased for larger buttons
    backgroundColor: '#f5f5f5',
    borderTopWidth: 1,
    borderTopColor: '#ddd',
  },
  modalOption: {
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#ddd',
  },
  selectedOption: {
    backgroundColor: '#d0f0d0',
  },
  modalOptionText: {
    fontSize: 16,
    color: '#333',
    textAlign: 'center',
  },
  modalCloseBtn: {
    marginTop: 15,
    backgroundColor: '#2e8b57',
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: 'center',
  },
  modalCloseText: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 16,
  },
  seedInfoContainer: {
    width: '90%',
    backgroundColor: '#fff',
    borderRadius: 18,
    padding: 25, // Increased for better spacing
    maxHeight: height * 0.7,
    elevation: 5,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 8,
  },
  infoName: {
    fontSize: 22,
    fontWeight: 'bold',
    marginBottom: 12,
    color: '#2e8b57',
    textAlign: 'center',
  },
  infoText: {
    fontSize: 16,
    marginBottom: 10, // Adjusted for better spacing
    color: '#444',
  },
  infoButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
  },
  infoButton: {
    flex: 1,
    marginHorizontal: 5,
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
  },
  input: {
    height: 45,
    borderColor: '#ccc',
    borderWidth: 1,
    borderRadius: 10,
    marginBottom: 8,
    paddingHorizontal: 12,
    fontSize: 16,
    color: '#333',
    backgroundColor: '#fff',
  },
  inputMultiline: {
    height: 80,
    borderColor: '#ccc',
    borderWidth: 1,
    borderRadius: 10,
    marginBottom: 15,
    paddingHorizontal: 12,
    paddingTop: 10,
    fontSize: 16,
    color: '#333',
    backgroundColor: '#fff',
  },
  inputText: {
    fontSize: 16,
    color: '#333',
    lineHeight: 45,
  },
  actionButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  leftButtonWrapper: {
    flex: 1,
    marginRight: 5,
  },
  rightButtonWrapper: {
    flex: 1,
    marginLeft: 5,
  },
  actionButton: {
    paddingVertical: 18, // Increased for larger buttons
    paddingHorizontal: 20,
    borderRadius: 14,
    alignItems: 'center',
    backgroundColor: '#2e8b57',
    elevation: 3,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
  },
  cancelButton: {
    backgroundColor: '#aaa',
  },
  actionButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 18, // Increased for readability
  },
  undoContainer: {
    position: 'absolute',
    bottom: 20,
    left: 20,
    right: 20,
    backgroundColor: '#333',
    padding: 10,
    borderRadius: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  undoText: {
    color: '#fff',
    fontSize: 16,
  },
  undoButtonText: {
    color: '#2e8b57',
    fontWeight: 'bold',
    fontSize: 16,
  },
});