import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

const stylesI = StyleSheet.create({
  container: {
    flex: 1,
    paddingTop: 50,
    paddingHorizontal: 16,
  },
  header: {
    fontSize: 28,
    fontWeight: 'bold',
    marginBottom: 12,
    color: '#333',
  },
  searchBar: {
    height: 40,
    borderColor: '#aaa',
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 10,
    marginBottom: 10,
    color: '#000',
  },
  filterSortRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  filterButton: {
    paddingVertical: 8,
    paddingHorizontal: 14,
    backgroundColor: '#0a84ff',
    borderRadius: 6,
  },
  filterButtonText: {
    color: '#fff',
    fontWeight: '600',
  },
  sortButton: {
    paddingVertical: 8,
    paddingHorizontal: 14,
    backgroundColor: '#32cd32',
    borderRadius: 6,
  },
  sortButtonText: {
    color: '#fff',
    fontWeight: '600',
  },
  noSeedsText: {
    fontSize: 16,
    color: '#888',
    alignSelf: 'center',
    marginTop: 20,
  },
  seedItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: '#e0f7fa',
    borderRadius: 8,
    marginBottom: 10,
  },
  seedName: {
    fontSize: 18,
    fontWeight: '600',
    color: '#00695c',
  },
  seedQuantity: {
    fontSize: 16,
    fontWeight: '500',
    color: '#004d40',
  },
  addButton: {
    position: 'absolute',
    bottom: 30,
    right: 20,
    backgroundColor: '#0a84ff',
    paddingVertical: 14,
    paddingHorizontal: 22,
    borderRadius: 30,
    elevation: 4,
  },
  addButtonText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 16,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  modalContainer: {
    backgroundColor: '#fff',
    borderRadius: 12,
    paddingVertical: 20,
    paddingHorizontal: 25,
    width: width * 0.85,
    maxHeight: height * 0.7,
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: '700',
    marginBottom: 15,
    color: '#222',
    textAlign: 'center',
  },
  modalOption: {
    paddingVertical: 12,
    borderBottomColor: '#ddd',
    borderBottomWidth: 1,
  },
  modalOptionText: {
    fontSize: 18,
    color: '#444',
    textAlign: 'center',
  },
  selectedOption: {
    backgroundColor: '#cce5ff',
  },
  modalCloseBtn: {
    marginTop: 15,
    paddingVertical: 10,
    backgroundColor: '#0a84ff',
    borderRadius: 8,
  },
  modalCloseText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 16,
    textAlign: 'center',
  },
  seedInfoContainer: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 20,
    width: width * 0.9,
    maxHeight: height * 0.8,
  },
  infoName: {
    fontSize: 26,
    fontWeight: 'bold',
    marginBottom: 10,
    color: '#00796b',
    textAlign: 'center',
  },
  infoText: {
    fontSize: 18,
    marginBottom: 6,
    color: '#004d40',
  },
  infoButtons: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 15,
  },
  infoButton: {
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 8,
  },
  buttonText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 16,
    textAlign: 'center',
  },
  addSeedModalContainer: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 20,
    paddingBottom: 40,
    width: width * 0.9,
    alignSelf: 'center',
  },
  input: {
    borderWidth: 1,
    borderColor: '#aaa',
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 8,
    fontSize: 16,
    marginBottom: 12,
    color: '#000',
  },
  pickerButton: {
    borderWidth: 1,
    borderColor: '#aaa',
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 14,
    marginBottom: 12,
    justifyContent: 'center',
  },
  addSeedButtons: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 10,
  },
  saveButton: {
    backgroundColor: '#2E8B57',
    paddingVertical: 12,
    paddingHorizontal: 30,
    borderRadius: 8,
    elevation: 3,
  },
  cancelButton: {
    backgroundColor: '#B22222',
    paddingVertical: 12,
    paddingHorizontal: 30,
    borderRadius: 8,
    elevation: 3,
  },
  undoContainer: {
    position: 'absolute',
    bottom: 10,
    left: 20,
    right: 20,
    backgroundColor: '#333',
    padding: 12,
    borderRadius: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    elevation: 6,
  },
  undoText: {
    color: '#fff',
    fontSize: 16,
  },
});

export default stylesI;
