import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 15,
    marginBottom: 20,
  },
  headerText: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#4CAF50', // Green text to stand out
    marginLeft: 10,
  },
  searchBar: {
    backgroundColor: '#FFFFFF',
    padding: 12,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    marginBottom: 20,
    fontSize: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  sortButton: {
    backgroundColor: '#FFFFFF',
    padding: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#4CAF50',
    flex: 1,
    marginHorizontal: 5,
    alignItems: 'center',
  },
  buttonText: {
    color: '#4CAF50',
    fontSize: 14,
    fontWeight: 'bold',
  },
  seedList: {
    flex: 1,
  },
  seedItem: {
    backgroundColor: '#81C784',
    padding: 15,
    marginVertical: 8,
    borderRadius: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  seedContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
  },
  seedText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: 'bold',
  },
  seedDetail: {
    color: '#E8F5E9',
    fontSize: 14,
    fontStyle: 'italic',
  },
  addButton: {
    backgroundColor: '#388E3C',
    padding: 15,
    borderRadius: 10,
    alignItems: 'center',
    marginTop: 3, // Reduced from 10 to 3 to move button higher
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  addButtonText: {
    color: '#FFFFFF',
    fontSize: 30,
    fontWeight: 'bold',
  },
  // Modal styles for category dropdown, seed info, and type/weather selection
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContent: {
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    padding: 20,
    width: 300,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  modalOption: {
    paddingVertical: 10,
    paddingHorizontal: 20,
    width: '100',
    alignItems: 'center',
  },
  modalOptionText: {
    fontSize: 16,
    color: '#4CAF50',
    fontWeight: 'bold',
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#4CAF50',
    marginBottom: 10,
  },
  expandedDetail: {
    fontSize: 14,
    color: '#424242',
    marginBottom: 5,
  },
  modalCloseButton: {
    backgroundColor: '#757575',
    padding: 10,
    borderRadius: 5,
    marginTop: 10,
  },
  modalCloseText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  modalEditButton: {
    backgroundColor: '#2196F3',
    padding: 10,
    borderRadius: 5,
    marginTop: 10,
    marginHorizontal: 5,
  },
  modalEditText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  modalDeleteButton: {
    backgroundColor: '#D32F2F',
    padding: 10,
    borderRadius: 5,
    marginTop: 10,
    marginHorizontal: 5,
  },
  modalDeleteText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  // Add seed modal styles
  input: {
    backgroundColor: '#F5F5F5',
    padding: 10,
    borderRadius: 5,
    marginBottom: 10,
    width: '100%',
    fontSize: 16,
    borderWidth: 1,
    borderColor: '#E0E0E0',
  },
  inputWithSuffix: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F5F5F5',
    borderRadius: 5,
    marginBottom: 10,
    width: '100%',
    borderWidth: 1,
    borderColor: '#E0E0E0',
  },
  inputText: {
    flex: 1,
    padding: 10,
    fontSize: 16,
    color: '#333',
  },
  inputSuffix: {
    fontSize: 16,
    color: '#757575',
    paddingHorizontal: 10,
  },
  customPicker: {
    backgroundColor: '#F5F5F5',
    padding: 10,
    borderRadius: 5,
    marginBottom: 10,
    width: '100%',
    borderWidth: 1,
    borderColor: '#E0E0E0',
  },
  customPickerText: {
    fontSize: 16,
    color: '#333',
  },
  placeholderText: {
    color: '#757575',
  },
  modalButtonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    marginTop: 10,
  },
  modalCancelButton: {
    backgroundColor: '#B0BEC5',
    padding: 10,
    borderRadius: 5,
  },
  modalCancelText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  modalAddButton: {
    backgroundColor: '#388E3C',
    padding: 10,
    borderRadius: 5,
  },
  modalAddText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  // Undo message styles
  undoContainer: {
    flexDirection: 'row',
    backgroundColor: '#424242',
    padding: 10,
    borderRadius: 5,
    marginVertical: 10,
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  undoText: {
    color: '#FFFFFF',
    fontSize: 14,
  },
  undoButtonText: {
    color: '#81C784',
    fontSize: 14,
    fontWeight: 'bold',
  },
  // No seeds message style
  noSeedsText: {
    textAlign: 'center',
    color: '#757575',
    fontSize: 16,
    marginVertical: 20,
    fontStyle: 'italic',
  },
});