import { StyleSheet, Dimensions } from 'react-native';

const { height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    resizeMode: 'cover',
    paddingTop: 40,
    paddingHorizontal: 20,
  },
  header: {
    marginBottom: 10,
    alignItems: 'center',
  },
  headerText: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#2E8B57',
  },
  searchBar: {
    height: 40,
    borderColor: '#2E8B57',
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 10,
    marginBottom: 10,
    color: '#000',
    backgroundColor: '#fff',
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  sortButton: {
    backgroundColor: '#2E8B57',
    paddingVertical: 8,
    paddingHorizontal: 15,
    borderRadius: 8,
  },
  buttonText: {
    color: '#fff',
    fontWeight: '600',
  },
  noSeedsText: {
    textAlign: 'center',
    marginTop: 20,
    fontSize: 16,
    color: '#555',
  },
  seedItem: {
    backgroundColor: '#e0f2f1',
    padding: 15,
    marginBottom: 8,
    borderRadius: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  seedName: {
    fontSize: 18,
    fontWeight: '600',
    color: '#2E8B57',
  },
  seedQuantity: {
    fontSize: 16,
    color: '#555',
  },
  addButton: {
    position: 'absolute',
    bottom: 30,
    right: 20,
    backgroundColor: '#2E8B57',
    paddingVertical: 15,
    paddingHorizontal: 25,
    borderRadius: 50,
    elevation: 5,
  },
  addButtonText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 16,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    width: '80%',
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 20,
    maxHeight: height * 0.6,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '700',
    marginBottom: 10,
    color: '#2E8B57',
    textAlign: 'center',
  },
  modalDivider: {
    height: 1,
    backgroundColor: '#ccc',
    marginBottom: 10,
  },
  modalOption: {
    paddingVertical: 12,
    paddingHorizontal: 10,
    borderRadius: 8,
    marginBottom: 8,
  },
  selectedOption: {
    backgroundColor: '#2E8B57',
  },
  modalOptionText: {
    fontSize: 16,
    color: '#2E8B57',
  },
  modalCloseBtn: {
    marginTop: 10,
    paddingVertical: 10,
    borderRadius: 8,
    backgroundColor: '#B22222',
  },
  modalCloseText: {
    color: '#fff',
    fontWeight: '700',
    textAlign: 'center',
  },
  seedInfoContainer: {
    width: '85%',
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 20,
  },
  modalContent: {
    marginBottom: 10,
  },
  infoName: {
    fontSize: 22,
    fontWeight: '700',
    marginBottom: 10,
    color: '#2E8B57',
    textAlign: 'center',
  },
  infoText: {
    fontSize: 16,
    marginBottom: 6,
    color: '#333',
  },
  infoButtons: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 15,
  },
  infoButton: {
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 8,
  },
  addSeedModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  addSeedModalContainer: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 20,
    maxHeight: height * 0.8,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  closeButton: {
    padding: 5,
  },
  input: {
    borderWidth: 1,
    borderColor: '#2E8B57',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginBottom: 10,
    color: '#000',
  },
  inputText: {
    fontSize: 16,
  },
  inputMultiline: {
    borderWidth: 1,
    borderColor: '#2E8B57',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginBottom: 10,
    height: 80,
    textAlignVertical: 'top',
    color: '#000',
  },
  modalFooter: {
    marginTop: 10,
  },
  actionButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  leftButtonWrapper: {
    flex: 1,
    marginRight: 5,
  },
  rightButtonWrapper: {
    flex: 1,
    marginLeft: 5,
  },
  actionButton: {
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  actionButtonText: {
    fontWeight: '700',
    fontSize: 16,
  },
  loginPromptContainer: {
    width: '80%',
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 20,
    alignItems: 'center',
  },
  loginPromptText: {
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 20,
    color: '#2E8B57',
  },
  loginPromptButton: {
    backgroundColor: '#2E8B57',
    paddingVertical: 12,
    paddingHorizontal: 30,
    borderRadius: 8,
    marginBottom: 10,
  },
  loginPromptButtonText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 16,
  },
  loginPromptCloseButton: {
    paddingVertical: 10,
    paddingHorizontal: 30,
  },
  loginPromptCloseButtonText: {
    color: '#2E8B57',
    fontWeight: '700',
    fontSize: 16,
  },
  undoContainer: {
    position: 'absolute',
    bottom: 100,
    left: 20,
    right: 20,
    backgroundColor: '#333',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  undoText: {
    color: '#fff',
    fontSize: 16,
  },
  undoButtonText: {
    color: '#2E8B57',
    fontWeight: '700',
    fontSize: 16,
  },
});
